// <auto-generated />
namespace IGCV_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agenda_attribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agenda_attribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201612122217572_agenda_attribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
