// <auto-generated />
namespace IGCV_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class made_agenda_Description_optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(made_agenda_Description_optional));
        
        string IMigrationMetadata.Id
        {
            get { return "201703152031329_made_agenda_Description_optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
