// <auto-generated />
namespace IGCV_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_mail_attach_flag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_mail_attach_flag));
        
        string IMigrationMetadata.Id
        {
            get { return "201704071115249_added_mail_attach_flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
